services:
  website:
    profiles:
      - website
    build:
      context: .
      dockerfile: Dockerfile.website
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-phpfpm/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '9003:9003'
    expose:
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      SUPERVISOR_PHP_USER: sail
    volumes:
      - '${LOCAL_WEBSITE_PATH}:/var/www/website'
    networks:
      - sail
    depends_on:
      - mysql
      - pgsql
      - redis

  utils:
    profiles:
      - utils
    build:
      context: .
      dockerfile: Dockerfile.utils
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-utils/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '${LOCAL_UTILS_PATH}:/var/opt/utils'
      - '${LOCAL_DOCKER_PATH}/after_files:/var/opt/after_files'  # Mount credentials
    networks:
      - sail
    depends_on:
      - mysql
      - pgsql
      - redis
    # Override the default command to keep container running
    command: tail -f /dev/null

  data-aggregator:
    profiles:
      - data-aggregator
    build:
      context: .
      dockerfile: Dockerfile.data-aggregator
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-aggregator/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9004:9004'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
      SETUP_DB_HOST: '${DA_DB_HOST}'
      SETUP_DB_PORT: '${DA_DB_PORT}'
      SETUP_DB_DATABASE: '${DA_DB_DATABASE}'
    volumes:
      - '${LOCAL_DATA_AGGREGATOR_PATH}:/var/www/data-aggregator'
      - '${LOCAL_UTILS_PATH}/dumps:/var/opt/dumps'
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  data-service-assets:
    profiles:
      - data-service-assets
    build:
      context: .
      dockerfile: Dockerfile.data-service-assets
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-service-assets/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9005:9005'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
      SETUP_DB_HOST: '${DS_ASSETS_DB_HOST}'
      SETUP_DB_PORT: '${DS_ASSETS_DB_PORT}'
      SETUP_DB_DATABASE: '${DS_ASSETS_DB_DATABASE}'
    volumes:
      - '${LOCAL_DATA_SERVICE_ASSETS_PATH}:/var/www/data-service-assets'
      - '${LOCAL_UTILS_PATH}/dumps:/var/opt/dumps'
    networks:
      - sail
    depends_on:
      - mysql

  data-service-styles:
    profiles:
      - data-service-styles
    build:
      context: .
      dockerfile: Dockerfile.data-service-styles
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-service-styles/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9007:9007'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '${LOCAL_DATA_SERVICE_STYLES_PATH}:/var/www/data-service-styles'
      - '${LOCAL_UTILS_PATH}/dumps:/var/opt/dumps'
      - './sqlite/init-databases.sh:/usr/local/bin/sqlite-init-databases.sh'
    networks:
      - sail

  data-service-archives:
    profiles:
      - data-service-archives
    build:
      context: .
      dockerfile: Dockerfile.data-service-archives
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-service-archives/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9009:9009'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
      SETUP_DB_HOST: '${DS_ARCHIVES_DB_HOST}'
      SETUP_DB_PORT: '${DS_ARCHIVES_DB_PORT}'
      SETUP_DB_DATABASE: '${DS_ARCHIVES_DB_DATABASE}'
      SETUP_DB_USERNAME: '${DS_ARCHIVES_DB_USERNAME}'
      SETUP_DB_PASSWORD: '${DS_ARCHIVES_DB_PASSWORD}'
    volumes:
      - '${LOCAL_DATA_SERVICE_ARCHIVES_PATH}:/var/www/data-service-archives'
      - '${LOCAL_UTILS_PATH}/dumps:/var/opt/dumps'
    networks:
      - sail
    depends_on:
      - pgsql

  data-enhancer:
    profiles:
      - data-enhancer
    build:
      context: .
      dockerfile: Dockerfile.data-enhancer
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-enhancer/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9006:9006'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
      SETUP_DB_HOST: '${DATA_ENHANCER_DB_HOST}'
      SETUP_DB_PORT: '${DATA_ENHANCER_DB_PORT}'
      SETUP_DB_DATABASE: '${DATA_ENHANCER_DB_DATABASE}'
    volumes:
      - '${LOCAL_DATA_ENHANCER_PATH}:/var/www/data-enhancer'
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  journeymaker-client:
    profiles:
      - journeymaker-client
    build:
      context: .
      dockerfile: Dockerfile.journeymaker-client
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-journeymaker-client/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9008:9008'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '${LOCAL_JOURNEYMAKER_CLIENT_PATH}:/var/www/journeymaker-client'
    networks:
      - sail

  data-hub-foundation:
    profiles:
      - data-hub-foundation
    build:
      context: .
      dockerfile: Dockerfile.data-hub-foundation
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-hub-foundation/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9010:9010'
    expose:
      - "9000"
      - "80"
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '${LOCAL_DATA_HUB_FOUNDATION_PATH}:/var/www/data-hub-foundation'
    networks:
      - sail

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DA_DB_DATABASE}'
      MYSQL_USER: '${DA_DB_USERNAME}'
      MYSQL_PASSWORD: '${DA_DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - '${LOCAL_DATA_AGGREGATOR_PATH}/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      - './mysql/init-databases.sql:/docker-entrypoint-initdb.d/20-init-databases.sql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DA_DB_PASSWORD}'
      retries: 3
      timeout: 5s

  pgsql:
    image: 'pgvector/pgvector:pg16-trixie'
    ports:
      - '54320:5432'
    environment:
      PGPASSWORD: '${WEB_DB_PASSWORD:-secret}'
      POSTGRES_DB: '${WEB_DB_DATABASE}'
      POSTGRES_USER: '${WEB_DB_USERNAME}'
      POSTGRES_PASSWORD: '${WEB_DB_PASSWORD:-secret}'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
      - './pgsql/init-databases.sh:/docker-entrypoint-initdb.d/20-init-databases.sh'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${WEB_DB_DATABASE}'
        - '-U'
        - '${WEB_DB_USERNAME}'
      retries: 3
      timeout: 5s

  data-service-artist-enrichment:
    profiles:
      - data-service-artist-enrichment
    build:
      context: .
      dockerfile: Dockerfile.data-service-artist-enrichment
      args:
        WWWGROUP: '${WWWGROUP}'
    image: aic-data-service-artist-enrichment/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      SETUP_DB_HOST: '${DS_ARTIST_ENRICHMENT_DB_HOST}'
      SETUP_DB_PORT: '${DS_ARTIST_ENRICHMENT_DB_PORT}'
      SETUP_DB_DATABASE: '${DS_ARTIST_ENRICHMENT_DB_DATABASE}'
      SETUP_DB_USERNAME: '${DS_ARTIST_ENRICHMENT_DB_USERNAME}'
      SETUP_DB_PASSWORD: '${DS_ARTIST_ENRICHMENT_DB_PASSWORD}'
    volumes:
      - '${LOCAL_DATA_SERVICE_ARTIST_ENRICHMENT_PATH}:/var/www/data-service-artist-enrichment'
      - '${LOCAL_DOCKER_PATH}/after_files:/var/opt/after_files'
    networks:
      - sail
    depends_on:
      - pgsql
      - data-aggregator
    command: tail -f /dev/null

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '${LOCAL_WEBSITE_PATH}:/var/www/website'
      - '${LOCAL_DATA_AGGREGATOR_PATH}:/var/www/data-aggregator'
      - '${LOCAL_DATA_SERVICE_ASSETS_PATH}:/var/www/data-service-assets'
      - '${LOCAL_DATA_SERVICE_STYLES_PATH}:/var/www/data-service-styles'
      - '${LOCAL_JOURNEYMAKER_CLIENT_PATH}:/var/www/journeymaker-client'
      - '${LOCAL_DATA_ENHANCER_PATH}:/var/www/data-enhancer'
      - '${LOCAL_DATA_SERVICE_ARCHIVES_PATH}:/var/www/data-service-archives'
      - '${LOCAL_DATA_SERVICE_ARTIST_ENRICHMENT_PATH}:/var/www/data-service-artist-enrichment'
    networks:
      sail:
        aliases:
          - www-dev.artic.edu
          - admin.www-dev.artic.edu
          - kiosk.www-dev.artic.edu
          - api-dev.artic.edu
          - assets-data-dev.artic.edu
          - enhancer-data-dev.artic.edu
          - archives-data-dev.artic.edu
          - artist-enrichment-data-dev.artic.edu
          - journeymaker-dev.artic.edu
    restart: unless-stopped

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
