CREATE DATABASE IF NOT EXISTS `data-aggregator`;
GRANT ALL PRIVILEGES ON `data-aggregator`.* TO '${DA_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON `data-enhancer`.* TO '${DA_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;