CREATE DATABASE IF NOT EXISTS `data-aggregator`;
CREATE DATABASE IF NOT EXISTS `testing`;
CREATE DATABASE IF NOT EXISTS `data-enhancer`;
CREATE DATABASE IF NOT EXISTS `data-service-assets`;
GRANT ALL PRIVILEGES ON `data-aggregator`.* TO '${DA_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON `testing`.* TO '${DA_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON `data-enhancer`.* TO '${DATA_ENHANCER_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON `data-service-assets`.* TO '${DS_ASSETS_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
