CREATE DATABASE vectors;
CREATE DATABASE website;

GRANT ALL PRIVILEGES ON DATABASE vectors TO sail;
GRANT ALL PRIVILEGES ON DATABASE website TO sail;

\c sail;
CREATE EXTENSION IF NOT EXISTS vector;

\c vectors;
CREATE EXTENSION IF NOT EXISTS vector;